INSERT INTO listuser (ID , USERNAME , CLIENT , LOGIN ) VALUES(1,'FaucheHe', 'MEDIA\RTSC015675','OPTISERVICE');
INSERT INTO listuser (ID , USERNAME , CLIENT , LOGIN ) VALUES(2,'ZaglioMi', 'MEDIA\RTSC045234','OPTISERVICE');
INSERT INTO listuser (ID , USERNAME , CLIENT , LOGIN ) VALUES(3,'uhlmanMi', 'MEDIA\RTSC098713','OPTISERVICE');
