DROP TABLE IF EXISTS listuser;

CREATE SEQUENCE listuser_pkey;

CREATE TABLE listuser (
  id INT NOT NULL PRIMARY KEY ,
  username VARCHAR(500) DEFAULT NULL,
  client VARCHAR(500) DEFAULT NULL,
  login VARCHAR(500) DEFAULT NULL

);


